### ISSUE TITLE
Collaboration opportunity? 

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [ryanwoodsmall/crosware#4]
https://github.com/OneOpenTeam/PlasmiumOS

**Comment by ryanwoodsmall** [comment]
I'm not sure I follow. The repo you sent is empty and I can't tell what it's supposed to be.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> I'm not sure I follow. The repo you sent is empty and I can't tell what it's supposed to be.


The repo is a temporary placeholder, while these 3 issues pseudo explains what the goal is.


https://github.com/OneOpenTeam/PlasmiumOS/issues/1

https://github.com/OneOpenTeam/PlasmiumOS/issues/2

https://github.com/OneOpenTeam/PlasmiumOS/issues/3

**Comment by ryanwoodsmall** [comment]
I looked at some of those links and I'm still unclear. What exactly is the end goal? Is there a succinct statement along the lines of "We want to achieve X for Y, using technologies A/B/C?"

For the crosware project, the goal was "I want vim with syntax highlighting on ChromeOS in dev mode, not using Gentoo or the janky (at the time) dev tools Google supplied." I knew I wanted an on-device compiler with standalone static libraries and binaries where possible; I'd fought too much too often with shared libs on embedded linux devices. That was pretty much it. From there it spread down to basic prereqs:

- I need a compiler (gcc, binutils)
- a std C lib (musl)
- a userspace (busybox+toybox)
- tools (make, GNU sed, gawk, patch, diff, ...)
- libs (ncurses, ...)

This is just to get to vim with syntax highlighting. Once I had a skeleton it spread the other way - "wouldn't it be nice to have a text web browser, links and/or lynx?" That means... openssl or libressl, openssl means perl, etc. etc. etc. At some point it became "okay now I have OpensSSL and Perl now, wouldn't it be nice to have a working non-Java native git?" Meaning curl, TLS/SSL certificates, and possibly an SSH client (openssh, dropbear, ...) if one is not available. By that point the project could build its own compilers and support its own development, i.e., it was fully bootstrapped and buildable ex nihilo in a Docker container, with _most_ recipes also working on ChromeOS.

This long-winded description of my goals and path isn't to say you have to or even should do things this way, but I straight up cannot tell what you're trying to accomplish here. The links frankly don't help much as it just seems to be a smattering of random ideas/technologies. IPFS? KDE Plasma? ChromiumOS builds w/Thorium? How do these things integrate, work together, compliment each other, etc.?

So: what are you going for here?

**Comment by ryanwoodsmall** [comment]
I'm going to close this issue, but I looked at some of the issues you've been opening in other projects. A word of advice, feel free to take it or leave it: some of the integrations/etc. you're proposing are monumental efforts, and not only do you have no real code to show, there are - again - no clearly-communicated goals, no mockups/wireframes/concepts for MVP, &c. From a maintainer standpoint, these kinds of issues are frankly worse than spam, since I can just delete obvious spam; not only is that not possible here, but I (and others) have had to look at what you linked in our projects to try to make sense of what you're suggesting/requesting/proposing/???, only to come to the conclusion there's not a serious request here.

I'm just some guy on the internet, most of the people you're interacting with on smaller projects are just folks doing this because they want to. I only have a couple of small projects I focus on these days, but I have code here, previously had projects on Google Code, etc. If you have a portfolio of work, when requesting collaboration you need to show that work. If you don't have work to show, enthusiasm can take you so far, but you need more than that - a technical diagram, draft of a spec/system design, white paper, pseudocode, etc. - anything. Otherwise there is nothing to collaborate on, and it feels like you're asking for free labor working on idea that's not fully-formed. Posting a bunch of links to a stranger without any further info feels a lot like asking someone else to do your homework.

There's a trope stemming from forums about an "ideas person" suggesting something approaching a full rebuild of all technology from the dawn of humanity to now, then offering that they "can make the website." The bigger the project or ask of someone else's time, the more work you need to put in before requesting that time and their attention. The more leg work I have to do to make heads or tails of something, the less likely I am to take it seriously.

Some of the concepts here are fundamental, operating system-level plumbing with higher-level UI wired to that plumbing. These are hard things, and they take resources - and not just people, who you need to convince in the first place. If you're essentially forking an OS/distro/userspace/etc. to modify, you now have to keep up with that fork, build with your own CI, test your changes against upstreams, etc. You've essentially inherited all the warts of any upstreams on top of your own changes, and if their priorities change in a way that makes your life harder, well, tough. Maintaining forks of large open source projects can literally become a job, or a near full-time equivalent, by itself. Never mind that you'll get bug reports that don't make sense, people refusing to elaborate while demanding you fix something, UI/UX nitpicks, etc.

I appreciate that you're thinking about hard things, and also that you found my project. However, this feels very much like an "I can make the website" scenario. I'd love for you to prove me wrong, but you have to put in more work.
